project_id = "roboonbdessuipvcpgve"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions]
verify_jwt = false

[functions.score-session-by-area]
verify_jwt = false